### ISSUE TITLE
thresholds need to be rounded up to product presentation

### ISSUE THREAD

**Issue by jjal** [fielded/angular-nav-thresholds#10]
all levels (min reorder max) need to be rounded up to product presentation. this will affect all calculations based on min / reorder / max, and will display in UI, matching up with users' expected allocations.

**Comment by jjal** [comment]
- [ ] dry good levels SHOULD be based on the max levels of their corresponding vaccines. e.g. 2ml syr is `total bcg max` / 20 - but don't need presentation rounding themselves as they come in single units

The way I read the ETL, we are calculating dry good levels by summing constituent vaccines' _target populations_ then reapplying the same allocation formula. However this is likely to produce a different number than simply adding the constituent vaccines' _max levels_.

**Comment by jjal** [comment]
full analysis of LGA levels:
[couch excel-lga-allocations.xlsx](https://github.com/fielded/angular-nav-thresholds/files/467430/couch.excel-lga-allocations.xlsx)

**Comment by tlvince** [comment]
> The way I read the ETL, we are calculating dry good levels by summing constituent vaccines' target populations then reapplying the same allocation formula

It _should_ be using the constituent calculated allocation, not target population.

**Comment by jjal** [comment]
NB: largest differences are with products based on aggregates of other max values. 
- the excel uses `round` on max values, to the nearest 20 (not `roundup`)
- this means that in some cases, especially for small lgas and large dose items (e.g. bcg, and its associated dry goods: 2ml recon syr -> 0.05 ad syr -> safety boxes) the excel ends up rounding max values down significantly.
- the rounding to 20 instead of product presentation probably makes up for a bit of this downward rounding in aggregate.
- dry goods which derive from this (2ml recon, 5ml recon, safety box) further `round`, again to 20, creating a large aggregate difference (see attached excel sheet)

_SO_
We will follow correct procedure and present the difference to national
- [ ] `roundup` all vaccine allocation values to presentation
- [ ] use vaccine allocation products to determine dry good allocations (don't use the target pop directly)
- the attached excel models this and results in a ~10% increase in allocation of dry goods.
- [ ] once allocations have been rounded and applied, let's redo this analysis to double check and report to nphcda.
  [couch excel-lga-allocations.xlsx](https://github.com/fielded/angular-nav-thresholds/files/467574/couch.excel-lga-allocations.xlsx)

**Comment by jjal** [comment]
links to https://github.com/fielded/nav-etl/issues/118

**Comment by jjal** [comment]
see comments on https://github.com/fielded/nav-etl/pull/129 

made a mistake when reviewing this. will need to round after thresholds are calculated to plan, not on each weeklyLevel.

**Comment by jjal** [comment]
reopened by waffle
