### ISSUE TITLE
Throw on missing mandatory params

### ISSUE THREAD

**Issue by tlvince** [fielded/angular-nav-thresholds#16]
Currently, if any of `location`, `stockCount` or `products` (and their required properties) are missing, we either return falsy or a default value (after #13). Better to be explicit and throw an error.

**Comment by patriciagarcia** [comment]
I am a little bit afraid of the throwing in this case, imho, better not to return any threshold and risking not being able to calculate KPIs (e.g. table cells appearing blank instead of red/green/yellow) than to throw and break the whole app.

Wouldn't it be better to just log the error?

cc/ @jjal
