### ISSUE TITLE
log to Google Analytics on error

### ISSUE THREAD

**Issue by patriciagarcia** [fielded/angular-nav-thresholds#28]
Related #16

**Comment by tlvince** [comment]
Now that I remember it, this is already done (generically) in the state dashboard via [google-analytics.decorator.js](https://github.com/fielded/nav-integrated-state-dashboard/blob/f13876c8f593bb6a7eb70051ab47bb98b9007658/src/app/common/google-analytics/google-analytics.decorator.js).
